void sendMessage(char *message);
void recieveMessage();
int compute_code(char* num);
char* itoa(int val, int base);
int is_prime(int num);
void decipher_by_primes();
void decipher();
void decipher_by_caesar(char* cipher, int rotate);
void format_print_server(char* message);
void format_print_user(char* message);